# Generated by Django 2.2.19 on 2022-04-16 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_decision', '0002_auto_20220416_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='end',
        ),
        migrations.AddField(
            model_name='posting',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name='posting',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
